instances:
  - name: elasticsearch
    dns:
      - elasticsearch
      - localhost
    ip:
      - 127.0.0.1
      - ::1
  - name: kibana
    dns:
      - kibana
      - localhost
    ip:
      - 127.0.0.1
      - ::1
  - name: apm-server
    dns:
      - apm-server
      - localhost
    ip:
      - 127.0.0.1
      - ::1
  - name: elasticsearch-01
    dns:
      - elasticsearch-01
      - localhost
    ip:
      - 127.0.0.1
      - ::1
  - name: kibana-01
    dns:
      - kibana-01
      - localhost
    ip:
      - 127.0.0.1
      - ::1
  - name: apm-server-01
    dns:
      - apm-server-01
      - localhost
    ip:
      - 127.0.0.1
      - ::1
  - name: elasticsearch-02
    dns:
      - elasticsearch-02
      - localhost
    ip:
      - 127.0.0.1
      - ::1
  - name: kibana-02
    dns:
      - kibana-02
      - localhost
    ip:
      - 127.0.0.1
      - ::1
  - name: apm-server-02
    dns:
      - apm-server-02
      - localhost
    ip:
      - 127.0.0.1
      - ::1
  - name: elasticsearch-03
    dns:
      - elasticsearch-03
      - localhost
    ip:
      - 127.0.0.1
      - ::1
  - name: kibana-03
    dns:
      - kibana-03
      - localhost
    ip:
      - 127.0.0.1
      - ::1
  - name: apm-server-03
    dns:
      - apm-server-03
      - localhost
    ip:
      - 127.0.0.1
      - ::1
